version: "3.8"

services:
  totheblessing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SYSTEM_CONSOLE_DISABLE_WRITELINE_BUFFERING=1
